# Generated by Django 5.2 on 2025-12-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_author"),
        ("todo", "0011_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="post",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
            preserve_default=False,
        ),
    ]
