# Generated by Django 5.2 on 2025-12-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_image"),
        ("blog", "0011_delete_comment"),
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_tasks",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_tasks",
                to="blog.post",
            ),
        ),
    ]
