# Generated by Django 5.2 on 2026-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_category_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog/"),
        ),
    ]
