# Generated by Django 5.2 on 2026-01-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="blog/cl-1.jpg", null=True, upload_to="blog/"
            ),
        ),
    ]
