# Generated by Django 5.2 on 2025-12-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_post_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
